# Build TauDEM_ext on macOS using AppleClang

name: Build with OpenMPI and GDAL using AppleClang on macOS

on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths-ignore:
      - 'data'
  pull_request:
      paths-ignore:
        - 'data'
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout TauDEM_ext
      uses: actions/checkout@v4

    - name: Setup xcode
      uses: maxim-lobanov/setup-xcode@v1

    - name: Install GDAL
      run: brew list gdal &>/dev/null || brew install gdal

    # - name: Setup MPI (use OpenMPI)
    #   uses: mpi4py/setup-mpi@v1
    #   with:
    #     mpi: openmpi
    - name: Install MPI
      run: brew list openmpi &>/dev/null || brew install openmpi

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j 4
