#include "GridLayering.h"
#ifdef SUPPORT_OMP
#include "omp.h"
#endif
#include <queue>
#include <set>
#include <climits>

#include "NormalizeFlowFractions.h"

using std::queue;
using std::set;

int find_flow_direction_index_ccw(const int fd) {
    for (int i = 1; i <= 8; i++) {
        if (fdccw[i] == fd) return i;
    }
    return -1;
}

int find_flow_direction_index_ccw(const int delta_row, const int delta_col) {
    for (int i = 1; i <= 8; i++) {
        if (drow[i] == delta_row && dcol[i] == delta_col) return i;
    }
    return -1;
}

int get_reversed_fdir(const int fd) {
    int fd_idx = find_flow_direction_index_ccw(fd);
    if (fd_idx < 0) return -1;
    int reversed_fd_idx = fd_idx > 4 ? fd_idx - 4 : fd_idx + 4;
    return fdccw[reversed_fd_idx];
}

vector<int> uncompress_flow_directions(const int compressed_fd) {
    // When invoke this function, the compressed_fd MUST be guaranteed to be POSITIVE!
    vector<int> flow_dirs; // record multiple flow directions by counter-clockwise
    if (compressed_fd <= 0) return flow_dirs;
    if (compressed_fd & 1) {
        flow_dirs.emplace_back(1);
    }
    if (compressed_fd & 128) {
        flow_dirs.emplace_back(128);
    }
    if (compressed_fd & 64) {
        flow_dirs.emplace_back(64);
    }
    if (compressed_fd & 32) {
        flow_dirs.emplace_back(32);
    }
    if (compressed_fd & 16) {
        flow_dirs.emplace_back(16);
    }
    if (compressed_fd & 8) {
        flow_dirs.emplace_back(8);
    }
    if (compressed_fd & 4) {
        flow_dirs.emplace_back(4);
    }
    if (compressed_fd & 2) {
        flow_dirs.emplace_back(2);
    }
    // Specific situation: {east, southeast} should be changed to {southeast, east} based on CCW
    if (flow_dirs.size() >= 2 && flow_dirs[0] == 1 && flow_dirs.back() == 2) {
        flow_dirs[0] = 2;
        flow_dirs.back() = 1;
    }
    return flow_dirs;
}

bool read_stream_vertexes(string stream_file, IntRaster *mask,
                          vector<vector<ROW_COL> > &stream_rc, int*& stream_matrix) {
    GDALVectorDSHandle stream_ds(OpenVector(stream_file.c_str()));
    if (nullptr == stream_ds) {
        cout << "Read stream shapefile failed!" << endl;
        return false;
    }
    OGRLayer *stream_lyr = stream_ds->GetLayer(0);
    if (wkbFlatten(stream_lyr->GetGeomType() != wkbLineString)) {
        cout << "The stream shapefile MUST be LINE!" << endl;
        return false;
    }
    // find Field index of "LINKNO"
    // todo, we should make this field name as an input argument. By LJ, 2025-09-15
    int fld_idx = stream_lyr->GetLayerDefn()->GetFieldIndex("LINKNO");
    int dstlink_idx = stream_lyr->GetLayerDefn()->GetFieldIndex("DSLINKNO");
    if (fld_idx < 0 || dstlink_idx < 0) {
        cout << "'LINKNO' and/or 'DSLINKNO' cannot be found in fields!" << endl;
        return false;
    }
    if (nullptr == stream_matrix) Initialize1DArray(mask->GetValidNumber(), stream_matrix,
                                                    mask->GetNoDataValue());
    vint ft_count = stream_lyr->GetFeatureCount();
    stream_lyr->ResetReading();
    for (vint i = 0; i < ft_count; i++) {
        OGRFeature *ft = stream_lyr->GetNextFeature();
        OGRGeometry *poGeometry = nullptr;
        OGRPoint ptTemp;
        poGeometry = ft->GetGeometryRef();
        if (nullptr == poGeometry) { continue; }
        if (wkbFlatten(poGeometry->getGeometryType()) != wkbLineString) { continue; }
        OGRLineString *poLineString = dynamic_cast<OGRLineString*>(poGeometry);
        int NumberOfVertices = poLineString->getNumPoints();
        vector<ROW_COL> tmp_rc;
        // Be caution: this code snippet only for Shapefile of stream generated by TauDEM,
        //             which should be updated when more stream vector sources are available.
        // todo, the line feature starts from the end of the stream, which should be caution when updates TauDEM.
        int stream_value = ft->GetFieldAsInteger(fld_idx);
        int dststream_value = ft->GetFieldAsInteger(dstlink_idx);
        for (int k = NumberOfVertices - 1; k >= 0; k--) {
            poLineString->getPoint(k, &ptTemp);
            ROW_COL rc = mask->GetPositionByCoordinate(ptTemp.getX(), ptTemp.getY());
            if (rc.first == -1 && rc.second == -1) { continue; } // Within the extent
            int pos_idx = mask->GetPosition(rc.first, rc.second);
            if (pos_idx < 0) { continue; }
            // Has valid value
            tmp_rc.emplace_back(rc);
            // if the stream has downstream, the end point should be assigned downstream's ID
            if (dststream_value > 0 && k == 0) continue;
            stream_matrix[pos_idx] = stream_value;
        }
        if (!tmp_rc.empty()) { stream_rc.emplace_back(tmp_rc); }
        OGRFeature::DestroyFeature(ft);
    }
    if (stream_rc.empty()) { return false; }

    return true;
}

void print_flow_fractions_mfdmd(FloatRaster *ffrac, int row, int col) {
    for (int i = 1; i <= 8; i++) {
        cout << ffrac->GetValue(row, col, i) << ",";
    }
}

struct SurpCmp {
    const vector<int> *S;
    SurpCmp(const vector<int> &S_): S(&S_) {
    }
    bool operator()(int a, int b) const {
        if ((*S)[a] != (*S)[b]) return (*S)[a] > (*S)[b];
        return a < b;
    }
};

struct CapHeadCmp {
    bool operator()(const std::pair<int, int> &a, const std::pair<int, int> &b) const {
        if (a.first != b.first) return a.first > b.first; // room descend
        return a.second < b.second; // layer ascend
    }
};

void BuildTargetsCappedWaterfillPrefix(int R, int K, int M, const vector<int> &Cap, vector<int> &T) {
    if (R <= 0) return;
    vector<char> active(K, 0);
    int act_cnt = 0;
    for (int l = 0; l < R; l++) {
        active[l] = 1;
        ++act_cnt;
    }
    int remain = M;
    for (;;) {
        if (act_cnt <= 0) break;
        int base = (act_cnt > 0 ? (remain / act_cnt) : 0);
        bool saturated = false;
        for (int l = 0; l < R; l++) {
            if (active[l]) {
                if (Cap[l] <= base) {
                    T[l] = Cap[l];
                    remain -= T[l];
                    active[l] = 0;
                    --act_cnt;
                    saturated = true;
                }
            }
        }
        if (!saturated) {
            for (int l = 0; l < R; l++) {
                if (active[l]) T[l] = base;
            }
            int rem = remain - base * act_cnt;
            if (rem > 0) {
                vector<std::pair<int, int> > head;
                head.reserve(act_cnt);
                for (int l = 0; l < R; l++) {
                    if (active[l]) {
                        int room = Cap[l] - T[l];
                        if (room < 0) room = 0;
                        head.push_back(std::make_pair(room, l));
                    }
                }
                std::sort(head.begin(), head.end(), CapHeadCmp());
                for (int i = 0; i < rem && i < CVT_INT(head.size()); i++) {
                    int l = head[i].second;
                    if (T[l] < Cap[l]) T[l] += 1;
                }
            }
            break;
        }
    }
}

// Static theoretic capacity of each layer
void ComputeLayerCaps(int N, int K, const vector<int> &Lmin, const vector<int> &Lmax, vector<int> &Cap) {
    Cap.assign(K, 0);
    for (int u = 0; u < N; u++) {
        int a = Lmin[u];
        int b = Lmax[u];
        if (a < 0) a = 0;
        if (b >= K) b = K - 1;
        for (int l = a; l <= b; ++l) {
            ++Cap[l];
        }
    }
}

int AutoDetectFixedSuffix_PrefixDynamic(const vector<vector<int> > &Buckets, const vector<int> &Count,
                                        const vector<int> &low, const vector<int> &high) {
    const int K = CVT_INT(Buckets.size());
    int R = 0;
    for (int l = K - 1; l >= 0; l--) {
        bool can_evac_up = false;
        for (size_t i = 0; i < Buckets[l].size(); i++) {
            int u = Buckets[l][i];
            if (low[u] < l) {
                can_evac_up = true;
                break;
            }
        }
        if (can_evac_up) break;

        int cap_prefix = 0;
        for (int x = 0; x <= l; x++) {
            const vector<int> &V = Buckets[x];
            for (size_t j = 0; j < V.size(); j++) {
                int v = V[j];
                if (low[v] <= l && l <= high[v]) cap_prefix++;
            }
        }
        if (cap_prefix == Count[l]) {
            ++R;
        } else {
            break;
        }
    }
    return R;
}

int AutoDetectFixedSuffix_Heuristic(int N, int K, bool fix_last, const vector<vector<int> > &Buckets,
                                    const vector<int> &Count, const vector<int> &low_dyn,
                                    const vector<int> *low_star_opt) {
    int last_ct = Count[K - 1];
    int Np = N;
    int tau = (K - 1) ? (Np / K) : 0;
    if (fix_last) {
        Np = N - last_ct;
        tau = (K - 1) ? (Np / (K - 1)) : 0;
    }

    int R = 0;
    for (int l = K - 1; l >= 0; l--) {
        const vector<int> &V = Buckets[l];
        int cnt = Count[l];

        if (cnt <= tau) {
            ++R;
            continue;
        } // not crowd, fixed directly

        bool exists_movable_up = false;
        for (size_t i = 0; i < V.size(); i++) {
            int u = V[i];
            if (low_dyn[u] < l) {
                exists_movable_up = true;
                break;
            }
            if (low_star_opt && (*low_star_opt)[u] < l) {
                exists_movable_up = true;
                break;
            }
        }
        if (!exists_movable_up) {
            ++R; // more but cannot move => fixed
        } else {
            break; // more and movable => stop here
        }
    }
    return R;
}

// Check how many lowest layers can be fixed during balancing layering
int AutoDetectFixedSuffix(const vector<vector<int> > &Buckets, const vector<int> &Lmin,
                          const vector<int> &Lmax, const vector<int> &Cap) {
    const int K = CVT_INT(Buckets.size());
    int fixed_suffix = 0;
    for (int l = K - 1; l >= 0; l--) {
        bool no_evac_up = true;
        for (size_t i = 0; i < Buckets[l].size(); i++) {
            int u = Buckets[l][i];
            if (Lmin[u] < l) {
                no_evac_up = false;
                break;
            }
        }
        bool no_headroom_in = (CVT_INT(Buckets[l].size()) == Cap[l]);
        if (no_evac_up && no_headroom_in) {
            ++fixed_suffix;
        } else break;
    }
    return fixed_suffix; // may be 0
}

int AutoDetectDynamicFixedSuffix(const vector<vector<int> > &Buckets,
                                 const vector<int> &low, const vector<int> &high,
                                 const vector<int> &mov_up, const vector<int> &mov_down,
                                 bool require_low_eq_high) {
    int K = CVT_INT(Buckets.size());
    int R = 0;
    for (int l = K - 1; l >= 0; l--) {
        bool dyn_lock = (mov_up[l] == 0 && mov_down[l] == 0);
        if (dyn_lock && require_low_eq_high) {
            for (size_t i = 0; i < Buckets[l].size(); i++) {
                int u = Buckets[l][i];
                if (!(low[u] == high[u] && low[u] == l)) {
                    dyn_lock = false;
                    break;
                }
            }
        }
        if (dyn_lock) ++R;
        else break;
    }
    return R;
}

/* prefix cap excluding suffix */
void ComputePrefixCapsExcludingSuffix(int N, int K, int prefix_end, const vector<int> &L,
                                      const vector<int> &Lmin, const vector<int> &Lmax, vector<int> &CapPrefix) {
    if (prefix_end <= 0) return;
    CapPrefix.assign(K, 0);
    for (int u = 0; u < N; u++) {
        if (L[u] < 0) continue;
        if (L[u] >= prefix_end) continue; // cell locates in fixed_suffix
        int a = Lmin[u];
        if (a < 0) a = 0;
        int b = Lmax[u];
        if (b >= K) b = K - 1;
        if (b < 0 || a >= K) continue;
        int Ls = (a > 0 ? a : 0);
        int Rs = (b < prefix_end - 1 ? b : (prefix_end - 1));
        if (Ls > Rs) continue;
        for (int l = Ls; l <= Rs; ++l)
            ++CapPrefix[l];
    }
}


int NearestDeficitLayer(int s, const vector<int> &S) {
    int K = CVT_INT(S.size());
    for (int dlt = 1; dlt < K; ++dlt) {
        int r = s + dlt, l = s - dlt;
        if (r < K && S[r] < 0) return r; // prefer the nearest downstream deficit layer
        if (l >= 0 && S[l] < 0) return l;
    }
    return -1;
}

// from layer s to layer d, find the nearest layer that between low_u and high_u, and S[t]<0; otherwise return -1
int PickNearestDeficitTarget(int s, int d, const vector<int> &S, int low_u, int high_u, int prefix_end) {
    if (d == s) return -1;
    int dir = (d > s) ? 1 : -1;
    for (int t = s + dir; (dir > 0 ? t <= d : t >= d); t += dir) {
        if (t >= prefix_end) break; // cannot enter frozen suffix
        if (t < low_u || t > high_u) continue;
        if (S[t] < 0) return t;
    }
    return -1;
}

int NeighborTightenRisk(int u, int t, int K, const vector<vector<int> > &Up, const vector<vector<int> > &Down,
                        const vector<int> &L, const vector<int> &low, const vector<int> &high,
                        const vector<int> &Lmin, const vector<int> &Lmax) {
    int risk = 0;
    // downstream: moving u to layer t will affect u's downstream's lowerst layerID
    for (size_t i = 0; i < Down[u].size(); i++) {
        // u's downstream cell
        int c = Down[u][i];
        int max_up = INT_MIN;
        for (size_t j = 0; j < Up[c].size(); j++) {
            // c's upstream cell
            int p = Up[c][j];
            int val = (p == u ? t : L[p]);
            if (val > max_up) max_up = val;
        }
        int new_low = (max_up == INT_MIN ? 0 : max_up + 1);
        if (new_low < Lmin[c]) new_low = Lmin[c];
        if (new_low < 0) new_low = 0;
        if (new_low > low[c]) risk++;
    }
    // upstream: moving u to layer t will affect u's upstream's highest layerID
    for (size_t i = 0; i < Up[u].size(); ++i) {
        // u's upstream cell
        int p = Up[u][i];
        int min_dn = INT_MAX;
        for (size_t j = 0; j < Down[p].size(); ++j) {
            // p's downstream cell
            int c = Down[p][j];
            int val = (c == u ? t : L[c]);
            if (val < min_dn) min_dn = val;
        }
        int new_high = (min_dn == INT_MAX ? (K - 1) : min_dn - 1);
        if (new_high > Lmax[p]) new_high = Lmax[p];
        if (new_high >= K) new_high = K - 1;
        if (new_high < high[p]) risk++;
    }
    return risk;
}

void CollectCandidates(int s, int d, int K, int prefix_end, const vector<vector<int> > &Buckets,
                       const vector<int> &L, const vector<int> &low, const vector<int> &high,
                       const vector<int> &Lmin, const vector<int> &Lmax,
                       const vector<vector<int> > &Up, const vector<vector<int> > &Down,
                       const vector<int> &S, bool require_deficit_target, const vector<int> *pCap,
                       int capMin, int capMax, double depth_penalty_weight, double scarcity_weight,
                       vector<Candidate> &out) {
    static const double A = 5.0; // slack
    static const double B = 2.0; // window
    static const double Cw = 1.0; // gateway
    static const double D = 1.0; // dist penalty
    static const double E = 2.0; // risk penalty
    static const double tiny = 1e-6;

    out.clear();
    const vector<int> &nodes = Buckets[s];

    for (size_t idx = 0; idx < nodes.size(); idx++) {
        int u = nodes[idx];
        int t = -1;

        if (require_deficit_target) {
            t = PickNearestDeficitTarget(s, d, S, low[u], high[u], prefix_end);
            if (t < 0) continue;
        } else {
            if (d > s) {
                int mh = (high[u] < d ? high[u] : d);
                int step = mh - s;
                if (step <= 0) continue;
                int need = Abs(d - s);
                if (step > need) step = need;
                t = s + step;
            } else if (d < s) {
                int ml = (low[u] > d ? low[u] : d);
                int step = s - ml;
                if (step <= 0) continue;
                int need = Abs(d - s);
                if (step > need) step = need;
                t = s - step;
            } else continue;
        }
        if (t >= prefix_end) continue; // forbid moving into frozen suffix

        int slk = Abs(t - s);
        int window = high[u] - low[u];
        if (window < 0) window = 0;
        int dist_penalty = Abs(t - d);
        int risk = NeighborTightenRisk(u, t, K, Up, Down, L, low, high, Lmin, Lmax);

        double score = 0.0;
        score += A * (double) slk;
        score += B * (double) window;
        if (Up[u].size() >= 2 || Down[u].size() >= 2) score += Cw;
        score -= D * (double) dist_penalty;
        score -= E * (double) risk;
        // downstream friction (optional)
        if (depth_penalty_weight > 0.0) {
            score -= depth_penalty_weight * (double) t;
        }
        // scarcity-based penalty (optional)
        if (pCap && scarcity_weight > 0.0 && capMax > capMin) {
            int cap_t = (*pCap)[t];
            double scarcity = 1.0 - (double) (cap_t - capMin) / (double) (capMax - capMin);
            score -= scarcity_weight * scarcity;
        }
        score -= tiny * (double) u;

        Candidate c;
        c.u = u;
        c.score = score;
        c.slack = slk;
        c.window = window;
        c.t = t;
        out.push_back(c);
    }
    std::sort(out.begin(), out.end(), CandidateCmp());
}


bool PickFeasibleDeficitAndCandidates(int s, const vector<int>& S, int K, int prefix_end,
                                      const vector<vector<int> >& Buckets,
                                      const vector<int>& L,
                                      const vector<int>& low, const vector<int>& high,
                                      const vector<int>& Lmin, const vector<int>& Lmax,
                                      const vector<vector<int> >& Up,
                                      const vector<vector<int> >& Down,
                                      bool strict_deficit_target,
                                      bool allow_intermediate_fallback,
                                      int& d_out,
                                      vector<Candidate>& cand_out,
                                      DeficitScanMode mode,
                                      const vector<int>* pCap,
                                      int capMin, int capMax,
                                      double depth_penalty_weight,
                                      double scarcity_weight) {
    vector<int> deficits;
    for (int l = 0; l < K; ++l) if (S[l] < 0) deficits.push_back(l);
    if (deficits.empty()) return false;

    if (mode == BIGGEST_DEFICIT_FIRST) {
        std::sort(deficits.begin(), deficits.end(), BigDefCmp(S, s));
        if (strict_deficit_target) {
            for (size_t i = 0; i < deficits.size(); ++i) {
                int d = deficits[i];
                cand_out.clear();
                CollectCandidates(s, d, K, prefix_end, Buckets, L, low, high, Lmin, Lmax, Up, Down, S,
                                  true, pCap, capMin, capMax,
                                  depth_penalty_weight, scarcity_weight, cand_out);
                if (!cand_out.empty()) {
                    d_out = d;
                    return true;
                }
            }
        }
        if (allow_intermediate_fallback) {
            for (size_t i = 0; i < deficits.size(); ++i) {
                int d = deficits[i];
                cand_out.clear();
                CollectCandidates(s, d, K, prefix_end, Buckets, L, low, high, Lmin, Lmax, Up, Down, S,
                                  false, pCap, capMin, capMax,
                                  depth_penalty_weight, scarcity_weight, cand_out);
                if (!cand_out.empty()) {
                    d_out = d;
                    return true;
                }
            }
        }
        return false;
    }

    vector<std::pair<int, int> > order;
    order.reserve(deficits.size());
    for (size_t i = 0; i < deficits.size(); ++i) {
        int d = deficits[i];
        order.push_back(std::make_pair(std::abs(d - s), d));
    }
    DistOrderCmp cmp(s, (mode == FARTHEST_FIRST));
    std::sort(order.begin(), order.end(), cmp);

    if (mode != BEST_BATCH_SCORE) {
        if (strict_deficit_target) {
            for (size_t i = 0; i < order.size(); ++i) {
                int d = order[i].second;
                cand_out.clear();
                CollectCandidates(s, d, K, prefix_end, Buckets, L, low, high, Lmin, Lmax, Up, Down, S,
                                  true, pCap, capMin, capMax,
                                  depth_penalty_weight, scarcity_weight, cand_out);
                if (!cand_out.empty()) {
                    d_out = d;
                    return true;
                }
            }
        }
        if (allow_intermediate_fallback) {
            for (size_t i = 0; i < order.size(); ++i) {
                int d = order[i].second;
                cand_out.clear();
                CollectCandidates(s, d, K, prefix_end, Buckets, L, low, high, Lmin, Lmax, Up, Down, S,
                                  false, pCap, capMin, capMax,
                                  depth_penalty_weight, scarcity_weight, cand_out);
                if (!cand_out.empty()) {
                    d_out = d;
                    return true;
                }
            }
        }
        return false;
    }

    int best_d = -1;
    double best_sum = -1e100;
    vector<Candidate> best_cand;

    for (size_t i = 0; i < order.size(); ++i) {
        int d = order[i].second;
        int need = 0; {
            int s_pos = S[s];
            int d_neg = -S[d];
            need = (s_pos < d_neg ? s_pos : d_neg);
        }
        if (need <= 0) continue;

        vector<Candidate> tmp;
        if (strict_deficit_target) {
            CollectCandidates(s, d, K, prefix_end, Buckets, L, low, high, Lmin, Lmax, Up, Down, S,
                              true, pCap, capMin, capMax,
                              depth_penalty_weight, scarcity_weight, tmp);
            if (!tmp.empty()) {
                int take = (int) tmp.size();
                if (take > need) take = need;
                double sum = 0.0;
                for (int k = 0; k < take; ++k) sum += tmp[k].score;
                if (sum > best_sum) {
                    best_sum = sum;
                    best_d = d;
                    best_cand = tmp;
                }
            }
        }
        if (allow_intermediate_fallback) {
            tmp.clear();
            CollectCandidates(s, d, K, prefix_end, Buckets, L, low, high, Lmin, Lmax, Up, Down, S,
                              false, pCap, capMin, capMax,
                              depth_penalty_weight, scarcity_weight, tmp);
            if (!tmp.empty()) {
                int take = (int) tmp.size();
                if (take > need) take = need;
                double sum = 0.0;
                for (int k = 0; k < take; ++k) sum += tmp[k].score;
                if (sum > best_sum) {
                    best_sum = sum;
                    best_d = d;
                    best_cand = tmp;
                }
            }
        }
    }
    if (best_d < 0) return false;
    d_out = best_d;
    cand_out = best_cand;
    return true;
}

void EvaluateBatchPotentialCounts(int s, const vector<Candidate> &cand, int need,
                                  const vector<int> &Count, const vector<int> &T,
                                  long long &phi1, long long &psi1) {
    vector<int> Ctmp = Count;
    int take = CVT_INT(cand.size());
    if (take > need) take = need;
    for (int k = 0; k < take; k++) {
        int t = cand[k].t;
        Ctmp[s] -= 1;
        Ctmp[t] += 1;
    }
    phi1 = Phi_L1(Ctmp, T);
    psi1 = Psi_L2(Ctmp, T);
}

void EvaluateBatchPotentialCountsPrefix(int s, const vector<Candidate> &cand, int need,
                                        const vector<int> &Count, const vector<int> &T,
                                        int prefix_end, long long &phi1_pref, long long &psi1_pref) {
    vector<int> Ctmp = Count;
    int take = CVT_INT(cand.size());
    if (take > need) take = need;
    for (int k = 0; k < take; k++) {
        int t = cand[k].t;
        Ctmp[s] -= 1;
        Ctmp[t] += 1;
    }
    phi1_pref = Phi_L1_Prefix(Ctmp, T, prefix_end);
    psi1_pref = Psi_L2_Prefix(Ctmp, T, prefix_end);
}

bool PickDeficitByPotentialAuto(int s, const vector<int> &S, int K, int prefix_end,
                                const vector<vector<int> > &Buckets,
                                const vector<int> &L, const vector<int> &low, const vector<int> &high,
                                const vector<int> &Lmin, const vector<int> &Lmax,
                                const vector<vector<int> > &Up, const vector<vector<int> > &Down,
                                const vector<int> &Count, const vector<int> &T,
                                bool allow_intermediate_fallback,
                                int &d_out, vector<Candidate> &cand_out,
                                const vector<int> *pCap, int capMin, int capMax,
                                double depth_penalty_weight, double scarcity_weight) {
    vector<int> deficits;
    for (int l = 0; l < prefix_end; l++) {
        if (S[l] < 0) deficits.push_back(l);
    }
    if (deficits.empty()) return false;

    long long best_phi = LLONG_MAX;
    long long best_psi = LLONG_MAX;
    int best_d = -1;
    vector<Candidate> best_cand;

    for (size_t i = 0; i < deficits.size(); ++i) {
        int d = deficits[i];
        int need = (S[s] < -S[d] ? S[s] : -S[d]);
        if (need <= 0) continue;

        // first try strictly allocate
        vector<Candidate> tmp;
        CollectCandidates(s, d, K, prefix_end, Buckets, L, low, high, Lmin, Lmax, Up, Down, S,
                          /*require_deficit_target=*/true,
                          pCap, capMin, capMax, depth_penalty_weight, scarcity_weight, tmp);
        if (!tmp.empty()) {
            long long phi1;
            long long psi1;
            // EvaluateBatchPotentialCounts(s, tmp, need, Count, T, phi1, psi1);
            EvaluateBatchPotentialCountsPrefix(s, tmp, need, Count, T, prefix_end, phi1, psi1);
            if (phi1 < best_phi || (phi1 == best_phi && psi1 < best_psi)) {
                best_phi = phi1;
                best_psi = psi1;
                best_d = d;
                best_cand = tmp;
            }
            continue; // if we got valid solution, then do not need to use fallback
        }

        // fallback: allowing to allocate in the intermediate layers
        if (allow_intermediate_fallback) {
            tmp.clear();
            CollectCandidates(s, d, K, prefix_end, Buckets, L, low, high, Lmin, Lmax, Up, Down, S,
                              /*require_deficit_target=*/false,
                              pCap, capMin, capMax, depth_penalty_weight, scarcity_weight, tmp);
            if (!tmp.empty()) {
                long long phi1;
                long long psi1;
                // EvaluateBatchPotentialCounts(s, tmp, need, Count, T, phi1, psi1);
                EvaluateBatchPotentialCountsPrefix(s, tmp, need, Count, T, prefix_end, phi1, psi1);
                if (phi1 < best_phi || (phi1 == best_phi && psi1 < best_psi)) {
                    best_phi = phi1;
                    best_psi = psi1;
                    best_d = d;
                    best_cand = tmp;
                }
            }
        }
    }

    if (best_d < 0) return false;
    d_out = best_d;
    cand_out = best_cand;
    return true;
}

bool TryEvictAndFillOnce(const vector<int> &S, int K, int prefix_end,
                         vector<vector<int> > &Buckets, vector<int> &L, vector<int> &Count,
                         const vector<int> &Lmin, const vector<int> &Lmax,
                         const vector<vector<int> > &Up, const vector<vector<int> > &Down,
                         vector<int> &low, vector<int> &high, const vector<int> &T) {
    vector<int> Surp;
    for (int l = 0; l < prefix_end; l++) {
        if (S[l] > 0) Surp.push_back(l);
    }
    if (Surp.empty()) return false;
    std::sort(Surp.begin(), Surp.end(), SurpCmp(S));
#ifdef _DEBUG
    std::printf("  [EVF] try: prefix_end=%d, SurpCnt=%d\n", prefix_end, (int)Surp.size());
#endif

    for (size_t si = 0; si < Surp.size(); si++) {
        int s = Surp[si];
        for (int b = 0; b < prefix_end; b++) {
            /* allow deficit layers as buffer */
            if (S[b] > 0) continue; // buffer can be balanced (S==0) or deficit (S<0)

            if (Buckets[s].empty() || Buckets[b].empty()) continue;

            // v: from s -> b
            vector<Candidate> cand_v;
            for (size_t i = 0; i < Buckets[s].size(); i++) {
                int v = Buckets[s][i];
                if (low[v] <= b && b <= high[v]) {
                    int window = high[v] - low[v];
                    if (window < 0) window = 0;
                    int slk = Abs(b - s);
                    int risk = NeighborTightenRisk(v, b, K, Up, Down, L, low, high, Lmin, Lmax);
                    double score = 5.0 * slk + 2.0 * window - 2.0 * risk - 1e-6 * v;
                    Candidate c;
                    c.u = v;
                    c.t = b;
                    c.slack = slk;
                    c.window = window;
                    c.score = score;
                    cand_v.push_back(c);
                }
            }
            if (cand_v.empty()) continue;
            std::sort(cand_v.begin(), cand_v.end(), CandidateCmp());

            // u: from b -> t_u (t_u in prefix, defict or balanced)
            vector<UPick> cand_u;
            for (size_t i = 0; i < Buckets[b].size(); i++) {
                int u = Buckets[b][i];
                for (int t = low[u]; t <= high[u]; t++) {
                    if (t == b) continue;
                    if (t >= prefix_end) continue;
                    if (S[t] > 0) continue;
                    /* optional: when buffer b is deficit, skip sending u to balanced */
                    if (S[b] < 0 && S[t] == 0) continue;

                    int slk = Abs(t - b);
                    int window = high[u] - low[u];
                    if (window < 0) window = 0;
                    int risk = NeighborTightenRisk(u, t, K, Up, Down, L, low, high, Lmin, Lmax);
                    double score = 5.0 * slk + 2.0 * window - 2.0 * risk - 1e-6 * u;
                    UPick pick;
                    pick.u = u;
                    pick.t = t;
                    pick.slack = slk;
                    pick.window = window;
                    pick.score = score;
                    cand_u.push_back(pick);
                }
            }
            if (cand_u.empty()) continue;
            std::sort(cand_u.begin(), cand_u.end(), UPickCmp());

            const int M = 8;
            int v_lim = CVT_INT(cand_v.size());
            if (v_lim > M) v_lim = M;
            int u_lim = CVT_INT(cand_u.size());
            if (u_lim > M) u_lim = M;

            long long best_phi1 = LLONG_MAX;
            long long best_psi1 = LLONG_MAX;
            int best_v = -1;
            int best_u = -1;
            int best_tu = -1;

            for (int iv = 0; iv < v_lim; iv++) {
                int v = cand_v[iv].u;
                for (int iu = 0; iu < u_lim; iu++) {
                    int u2 = cand_u[iu].u;
                    int t_u = cand_u[iu].t;
                    if (u2 == v) continue;

                    vector<int> Ctmp = Count;
                    Ctmp[s]--; // v: s -> b
                    Ctmp[b]++; // temp
                    Ctmp[b]--; // u: b -> t_u
                    Ctmp[t_u]++;

                    long long phi1 = Phi_L1_Prefix(Ctmp, T, prefix_end);
                    long long psi1 = Psi_L2_Prefix(Ctmp, T, prefix_end);
                    if (phi1 < best_phi1 || (phi1 == best_phi1 && psi1 < best_psi1)) {
                        best_phi1 = phi1;
                        best_psi1 = psi1;
                        best_v = v;
                        best_u = u2;
                        best_tu = t_u;
                    }
                }
            }

            if (best_v >= 0 && best_u >= 0) {
                // long long phi0 = Phi_L1(Count, T);
                // long long psi0 = Psi_L2(Count, T);
                long long phi0_pref = Phi_L1_Prefix(Count, T, prefix_end);
                long long psi0_pref = Psi_L2_Prefix(Count, T, prefix_end);
                vector<int> Ctmp = Count;
                Ctmp[s]--; // v: s -> b
                Ctmp[b]++; // temp
                Ctmp[b]--; // u: b -> t_u
                Ctmp[best_tu]++;
                long long phi1_pref = Phi_L1_Prefix(Ctmp, T, prefix_end);
                long long psi1_pref = Psi_L2_Prefix(Ctmp, T, prefix_end);

                if (phi1_pref < phi0_pref || (phi1_pref == phi0_pref && psi1_pref < psi0_pref)) {
#ifdef _DEBUG
                    std::printf("  [EVF] ACCEPT: s=%d  b=%d  v:%d -> %d  u:%d -> %d  Phi_pref:%lld->%lld Psi_pref:%lld->%lld\n",
                        s, b, best_v, b, best_u, best_tu, phi0_pref, phi1_pref, psi0_pref, psi1_pref);
#endif
                    // real execute
                    vector<int> moved;
                    PlaceOne(best_u, best_tu, L, Buckets, Count);
                    moved.push_back(best_u);
                    PlaceOne(best_v, b, L, Buckets, Count);
                    moved.push_back(best_v);
                    RefreshLocalBounds(moved, K, Up, Down, L, Lmin, Lmax, low, high);
                    return true; // accept and exit
                } else {
                    continue; // don't exit; try next (s, b)
                }
            }
        }
    }
    return false;
}

// ---------- Move one cell from source layer to target layer ----------
void PlaceOne(int u, int t, vector<int> &L, vector<vector<int> > &Buckets, vector<int> &Count) {
    int s = L[u];
    if (s == t) return; // source layer is the same with target layer
    vector<int> &src = Buckets[s];
    for (size_t i = 0; i < src.size(); i++) {
        if (src[i] == u) {
            src.erase(src.begin() + (int) i);
            break;
        }
    }
    Buckets[t].push_back(u);
    Count[s]--;
    Count[t]++;
    L[u] = t;
}

static void RefreshLocalBounds(const vector<int> &moved, int K,
                               const vector<vector<int> > &Up, const vector<vector<int> > &Down,
                               const vector<int> &L, const vector<int> &Lmin, const vector<int> &Lmax,
                               vector<int> &low, vector<int> &high) {
    const int N = CVT_INT(L.size());
    std::queue<int> q;
    vector<char> inq(N, 0);
    for (size_t i = 0; i < moved.size(); i++) {
        int u = moved[i];
        if (!inq[u]) {
            q.push(u);
            inq[u] = 1;
        }
        for (size_t j = 0; j < Up[u].size(); j++) {
            int p = Up[u][j];
            if (!inq[p]) {
                q.push(p);
                inq[p] = 1;
            }
        }
        for (size_t j = 0; j < Down[u].size(); j++) {
            int c = Down[u][j];
            if (!inq[c]) {
                q.push(c);
                inq[c] = 1;
            }
        }
    }
    while (!q.empty()) {
        int x = q.front();
        q.pop();
        inq[x] = 0;
        int nl;
        int nh;
        RecomputeBoundsOne(x, K, Up, Down, L, Lmin, Lmax, nl, nh);
        if (nl != low[x] || nh != high[x]) {
            low[x] = nl;
            high[x] = nh;
            for (size_t j = 0; j < Up[x].size(); j++) {
                int p = Up[x][j];
                if (!inq[p]) {
                    q.push(p);
                    inq[p] = 1;
                }
            }
            for (size_t j = 0; j < Down[x].size(); j++) {
                int c = Down[x][j];
                if (!inq[c]) {
                    q.push(c);
                    inq[c] = 1;
                }
            }
        }
    }
}

static void DebugComputeMovStats(
    const vector<vector<int> > &Buckets,
    const vector<int> &low,
    const vector<int> &high,
    vector<int> &mov_up,
    vector<int> &mov_down) {
    const int K = (int) Buckets.size();
    mov_up.assign(K, 0);
    mov_down.assign(K, 0);
    for (int l = 0; l < K; ++l) {
        for (size_t i = 0; i < Buckets[l].size(); ++i) {
            int u = Buckets[l][i];
            if (low[u] < l) mov_up[l]++;
            if (high[u] > l) mov_down[l]++;
        }
    }
}

static void DebugPrintSlice(
    int K, int show,
    const vector<int> &Count,
    const vector<int> &T,
    const vector<int> &mov_up,
    const vector<int> &mov_down
) {
#ifdef _DEBUG
    int S = (show < K ? show : K);
    for (int l = 0; l < S; ++l) {
        std::printf("  L%02d: C=%d T=%d up=%d dn=%d\n", l, Count[l], T[l], mov_up[l], mov_down[l]);
    }
    if (K > S) {
        std::printf("  ...\n");
        for (int l = (K - S); l < K; ++l) {
            std::printf("  L%02d: C=%d T=%d up=%d dn=%d\n", l, Count[l], T[l], mov_up[l], mov_down[l]);
        }
    }
#endif
}

#ifdef USE_MONGODB
GridLayering::GridLayering(const int id, MongoGridFs *gfs, const char *out_dir) : gfs_(gfs), use_mongo_(true),
    has_mask_(false), decimals_(4),
    fdtype_(FD_D8), output_dir_(out_dir), subbasin_id_(id),
    n_rows_(-1), n_cols_(-1), out_nodata_(-9999),
    n_valid_cells_(-1), n_layer_count_(-1), pos_index_(nullptr), pos_rowcol_(nullptr),
    mask_(nullptr), flowdir_(nullptr), flow_fraction_(nullptr), dem_(nullptr),
    flowdir_matrix_(nullptr), reverse_dir_(nullptr),
    flowfrac_matrix_(nullptr), stream_matrix_(nullptr),
    flow_in_num_(nullptr), flow_in_acc_(nullptr), flow_in_count_(0), flow_in_cells_(nullptr), flowin_fracs_(nullptr),
    flow_out_num_(nullptr), flow_out_acc_(nullptr), flow_out_count_(0), flow_out_cells_(nullptr), flowout_fracs_(nullptr),
    layers_updown_(nullptr), layers_downup_(nullptr), layers_evenly_(nullptr),
    layer_cells_updown_(nullptr), layer_cells_downup_(nullptr), layer_cells_evenly_(nullptr) {
}
#endif

GridLayering::GridLayering(const int id, const char *out_dir): gfs_(nullptr), use_mongo_(false),
    has_mask_(false), decimals_(4),
    fdtype_(FD_D8), output_dir_(out_dir), subbasin_id_(id),
    n_rows_(-1), n_cols_(-1), out_nodata_(-9999),
    n_valid_cells_(-1), n_layer_count_(-1), pos_index_(nullptr), pos_rowcol_(nullptr),
    mask_(nullptr), flowdir_(nullptr), flow_fraction_(nullptr), dem_(nullptr),
    flowdir_matrix_(nullptr), reverse_dir_(nullptr),
    flowfrac_matrix_(nullptr), stream_matrix_(nullptr),
    flow_in_num_(nullptr), flow_in_acc_(nullptr), flow_in_count_(0), flow_in_cells_(nullptr), flowin_fracs_(nullptr),
    flow_out_num_(nullptr), flow_out_acc_(nullptr), flow_out_count_(0), flow_out_cells_(nullptr), flowout_fracs_(nullptr),
    layers_updown_(nullptr), layers_downup_(nullptr), layers_evenly_(nullptr),
    layer_cells_updown_(nullptr), layer_cells_downup_(nullptr), layer_cells_evenly_(nullptr) {
}

GridLayering::~GridLayering() {
    delete flowdir_; // flowdir_matrix_ will be released too.
    delete flow_fraction_; // flowfrac_matrix_ will be released too for mfd only.
    delete dem_;
    if (has_mask_) delete mask_;
    if (nullptr != pos_index_) Release1DArray(pos_index_);
    if (nullptr != reverse_dir_) Release1DArray(reverse_dir_);
    if (nullptr != stream_matrix_) Release1DArray(stream_matrix_);
    if (nullptr != flow_in_num_) Release1DArray(flow_in_num_);
    if (nullptr != flow_in_acc_) Release1DArray(flow_in_acc_);
    if (nullptr != flow_in_cells_) Release1DArray(flow_in_cells_);
    if (nullptr != flowin_fracs_) Release1DArray(flowin_fracs_);
    if (nullptr != flow_out_num_) Release1DArray(flow_out_num_);
    if (nullptr != flow_out_acc_) Release1DArray(flow_out_acc_);
    if (nullptr != flow_out_cells_) Release1DArray(flow_out_cells_);
    if (nullptr != flowout_fracs_) Release1DArray(flowout_fracs_);
    if (nullptr != layers_updown_) Release1DArray(layers_updown_);
    if (nullptr != layers_downup_) Release1DArray(layers_downup_);
    if (nullptr != layers_evenly_) Release1DArray(layers_evenly_);
    if (nullptr != layer_cells_updown_) Release1DArray(layer_cells_updown_);
    if (nullptr != layer_cells_downup_) Release1DArray(layer_cells_downup_);
    if (nullptr != layer_cells_evenly_) Release1DArray(layer_cells_evenly_);
}

bool GridLayering::LoadChannelData() {
    if (stream_file_.empty()) {
        return true;
    }
    if (nullptr == stream_matrix_ && n_valid_cells_ > 0) {
        Initialize1DArray(n_valid_cells_, stream_matrix_, mask_->GetNoDataValue());
    } else return false;
    vector<vector<ROW_COL> > stream_rc;
    if (!read_stream_vertexes(stream_file_, mask_, stream_rc, stream_matrix_)) return false;

    for (vector<vector<ROW_COL> >::iterator it = stream_rc.begin(); it != stream_rc.end(); ++it) {
        // A line should have at least two points! This can be guaranteed by read_stream_vertexes()!
        if (it->size() < 2) continue;
        for (vector<ROW_COL>::iterator it2 = it->begin(); it2 != it->end() - 1; ++it2) {
            int delta_row = (it2 + 1)->first - it2->first;
            int delta_col = (it2 + 1)->second - it2->second;
            int fd_index = find_flow_direction_index_ccw(delta_row, delta_col);
            int pos = pos_index_[it2->first * n_cols_ + it2->second];
            // cout << it2->first << ", " << it2->second << ", " << pos << endl;
            for (int i = 1; i <= 8; i++) {
                flowfrac_matrix_[pos][i - 1] = out_nodata_;
                // flow_fraction_->SetValue(it2->first, it2->second,
                //                          flow_fraction_->GetNoDataValue(), i); // DO NOT MODIFY Raster data
            }
            if (fd_index < 0) { // this should not be happened, just in case!
                flowdir_matrix_[pos] = -1;
                // flowdir_->SetValue(it2->first, it2->second, -1); // DO NOT MODIFY Raster data
            } else {
                flowdir_matrix_[pos] = fdccw[fd_index];
                flowfrac_matrix_[pos][fd_index - 1] = 1.;
                // flowdir_->SetValue(it2->first, it2->second, fdccw[fd_index]);
                // flow_fraction_->SetValue(it2->first, it2->second, 1.f, fd_index);
            }
        }
        // cout << endl;
    }

    return true;
}


bool GridLayering::Execute() {
    if (!LoadData()) return false;
    // first, layering all grid cells in the watershed
    bool first = OutputFlowOut() && OutputFlowIn()
                    && GridLayeringFromSource()
                    && GridLayeringFromOutlet()
                    && GridLayeringEvenly();
    // (optional) second, layering only hillslope cells, by setting all channel cells as outlets
    bool second = true;
    // (optional) last, layering only channel cells
    bool third = true;
    if (!stream_file_.empty() && nullptr != stream_matrix_) {
        second = OutputFlowOut(1) && OutputFlowIn(1)
                    && GridLayeringFromSource(1)
                    && GridLayeringFromOutlet(1)
                    && GridLayeringEvenly(1);
        third = OutputFlowOut(2) && OutputFlowIn(2)
                    && GridLayeringFromSource(2)
                    && GridLayeringFromOutlet(2)
                    && GridLayeringEvenly(2);
    }
    return first && second && third;
}

void GridLayering::CalPositionIndex() {
    if (n_valid_cells_ > 0 && nullptr != pos_index_) return;
    Initialize1DArray(n_rows_ * n_cols_, pos_index_, -1);
    for (int i = 0; i < n_valid_cells_; i++) {
        pos_index_[pos_rowcol_[i][0] * n_cols_ + pos_rowcol_[i][1]] = i;
    }
}

void GridLayering::GetReverseDirMatrix(int mode/*=0*/) {
    if (nullptr != reverse_dir_) Release1DArray(reverse_dir_);
    Initialize1DArray(n_valid_cells_, reverse_dir_, 0);
    if (nullptr != flow_in_num_) Release1DArray(flow_in_num_);
    Initialize1DArray(n_valid_cells_, flow_in_num_, -1);
    if (nullptr != flow_in_acc_) Release1DArray(flow_in_acc_);
    Initialize1DArray(n_valid_cells_, flow_in_acc_, 0);
    // bool handle_stream = force_outlet_ && nullptr != stream_matrix_;
    for (int valid_idx = 0; valid_idx < n_valid_cells_; valid_idx++) {
        int i = pos_rowcol_[valid_idx][0]; // row
        int j = pos_rowcol_[valid_idx][1]; // col
        int flow_dir = flowdir_matrix_[valid_idx];
        if (flowdir_->IsNoData(i, j) || flow_dir <= 0) {
            // Avoid repeatedly change to nodata, since such cells can accept flow in
            if (reverse_dir_[valid_idx] == 0) {
                reverse_dir_[valid_idx] = out_nodata_;
            }
            continue;
        }
        int stream_dst = mode != 0 ? stream_matrix_[valid_idx] : -1;
        if (mode == 2 && FloatEqual(stream_dst, out_nodata_)) continue;
        if (flow_in_num_[valid_idx] == -1) flow_in_num_[valid_idx] = 0;
        vector<int> flow_dirs = uncompress_flow_directions(flow_dir);
        for (vector<int>::iterator it = flow_dirs.begin(); it != flow_dirs.end(); ++it) {
            int fd_idx = find_flow_direction_index_ccw(*it);
            int src_row = i + drow[fd_idx];
            int src_col = j + dcol[fd_idx];
            if (!mask_->ValidateRowCol(src_row, src_col) || mask_->IsNoData(src_row, src_col)) {
                continue;
            }
            int src_idx = pos_index_[src_row * n_cols_ + src_col];
            if (flow_in_num_[src_idx] == -1) flow_in_num_[src_idx] = 0;
            if (FloatEqual(reverse_dir_[src_idx], out_nodata_) || reverse_dir_[src_idx] < 0) {
                // Boundary cells may be NoData in flowdir_, but they can accept flow in
                reverse_dir_[src_idx] = 0;
            }
            int stream_src = mode != 0 ? stream_matrix_[src_idx] : -1;
            if (mode == 1 && stream_src > 0 && stream_dst > 0) {
                continue;
            }
            if (mode == 2 && FloatEqual(stream_src, out_nodata_)) continue;

            reverse_dir_[src_idx] += get_reversed_fdir(fdccw[fd_idx]);
            flow_in_num_[src_idx]++;
        }
    }
    flow_in_acc_[0] = flow_in_num_[0] < 0 ? 0 : flow_in_num_[0];
    flow_in_count_ = flow_in_num_[0] < 0 ? 0 : flow_in_num_[0];
    for (int idx = 1; idx < n_valid_cells_; idx++) {
        if (flow_in_num_[idx] < 0) {
            flow_in_acc_[idx] = flow_in_acc_[idx - 1];
            continue;
        }
        flow_in_count_ += flow_in_num_[idx];
        flow_in_acc_[idx] = flow_in_num_[idx] + flow_in_acc_[idx - 1];
    }
}

void GridLayering::OutputFilenames() {
    string prefix = ValueToString(subbasin_id_);
    flowin_index_name_ = prefix + "_FLOWIN_INDEX_" + fdtype_str_;
    flowin_frac_name_ = prefix + "_FLOWIN_FRACTION_" + fdtype_str_;
    flowout_index_name_ = prefix + "_FLOWOUT_INDEX_" + fdtype_str_;
    flowout_frac_name_ = prefix + "_FLOWOUT_FRACTION_" + fdtype_str_;

    flowin_index_hs_name_ = prefix + "_FLOWIN_INDEX_HILLSLOPE_" + fdtype_str_;
    flowin_frac_hs_name_ = prefix + "_FLOWIN_FRACTION_HILLSLOPE_" + fdtype_str_;
    flowout_index_hs_name_ = prefix + "_FLOWOUT_INDEX_HILLSLOPE_" + fdtype_str_;
    flowout_frac_hs_name_ = prefix + "_FLOWOUT_FRACTION_HILLSLOPE_" + fdtype_str_;

    layering_updown_name_ = prefix + "_ROUTING_LAYERS_UPDOWN_" + fdtype_str_;
    layering_downup_name_ = prefix + "_ROUTING_LAYERS_DOWNUP_" + fdtype_str_;
    layering_evenly_name_ = prefix + "_ROUTING_LAYERS_EVEN_" + fdtype_str_;

    layering_updown_hs_ = prefix + "_ROUTING_LAYERS_UPDOWN_HILLSLOPE_" + fdtype_str_;
    layering_downup_hs_ = prefix + "_ROUTING_LAYERS_DOWNUP_HILLSLOPE_" + fdtype_str_;
    layering_evenly_hs_ = prefix + "_ROUTING_LAYERS_EVEN_HILLSLOPE_" + fdtype_str_;

    layering_updown_ch_ = prefix + "_ROUTING_LAYERS_UPDOWN_CHANNEL_" + fdtype_str_;
    layering_downup_ch_ = prefix + "_ROUTING_LAYERS_DOWNUP_CHANNEL_" + fdtype_str_;
    layering_evenly_ch_ = prefix + "_ROUTING_LAYERS_EVEN_CHANNEL_" + fdtype_str_;
}


int GridLayering::BuildMultiFlowOutArray(int *&compressed_dir,
                                         int *&connect_count, int *&p_output) {
    p_output[0] = n_valid_cells_;
    int counter = 1;
    for (int valid_idx = 0; valid_idx < n_valid_cells_; valid_idx++) {
        int i = pos_rowcol_[valid_idx][0]; // row
        int j = pos_rowcol_[valid_idx][1]; // col
        /// count of flow out cells
        p_output[counter++] = connect_count[valid_idx]; // maybe 0
        if (connect_count[valid_idx] <= 0) {
            p_output[counter - 1] = 0;
            continue;
        }
        /// loop flow out directions
        vector<int> flow_dirs = uncompress_flow_directions(compressed_dir[valid_idx]);
        for (vector<int>::iterator it = flow_dirs.begin(); it != flow_dirs.end(); ++it) {
            int fd_idx = find_flow_direction_index_ccw(*it);
            if (!mask_->ValidateRowCol(i + drow[fd_idx], j + dcol[fd_idx]) ||
                mask_->IsNoData(i + drow[fd_idx], j + dcol[fd_idx])) {
                continue;
            }
            p_output[counter++] = pos_index_[(i + drow[fd_idx]) * n_cols_ + j + dcol[fd_idx]];
        }
    }
    return counter;
}

bool GridLayering::BuildFlowInCellsArray() {
    int n_output = flow_in_count_ + n_valid_cells_ + 1;
    if (nullptr != flow_in_cells_) Release1DArray(flow_in_cells_);
    Initialize1DArray(n_output, flow_in_cells_, 0);
    int n_output2 = BuildMultiFlowOutArray(reverse_dir_, flow_in_num_, flow_in_cells_);
    if (n_output2 != n_output) {
        cout << "BuildFlowInCellsArray failed!" << endl;
        return false;
    }
    return true;
}

void GridLayering::CountFlowOutCells(int mode/*=0*/) {
    if (nullptr != flow_out_num_) Release1DArray(flow_out_num_);
    Initialize1DArray(n_valid_cells_, flow_out_num_, -1);
    if (nullptr != flow_out_acc_) Release1DArray(flow_out_acc_);
    Initialize1DArray(n_valid_cells_, flow_out_acc_, 0);
    //bool handle_stream = force_outlet_ && nullptr != stream_matrix_;
//#pragma omp parallel for
    for (int index = 0; index < n_valid_cells_; index++) {
        int i = pos_rowcol_[index][0]; // row
        int j = pos_rowcol_[index][1]; // col
        if (flowdir_->IsNoData(i, j) || flowdir_matrix_[index] < 0) continue;
        int stream_src = mode != 0 ? stream_matrix_[index]: -1;
        if (mode == 2 && FloatEqual(stream_src, out_nodata_)) continue;

        if (flow_out_num_[index] == -1) flow_out_num_[index] = 0;

        int flow_dir = flowdir_matrix_[index];
        vector<int> flow_dirs = uncompress_flow_directions(flow_dir);
        int org_down_num = flow_dirs.size();
        for (vector<int>::iterator it = flow_dirs.begin(); it != flow_dirs.end(); ++it) {
            int fd_idx = find_flow_direction_index_ccw(*it);
            int dst_row = i + drow[fd_idx];
            int dst_col = j + dcol[fd_idx];
            if (!mask_->ValidateRowCol(dst_row, dst_col) || mask_->IsNoData(dst_row, dst_col)) {
                // means flow out of the mask boundary, so we should remove this direction
                // Here, we only handle the flow direction, this is unrelated with flow direction algorithms.
                // For multiple flow direction algorithms, the flow fractions should be handled in other places.
                flowdir_matrix_[index] -= (*it);
                continue;
            }
            int dst_idx = pos_index_[dst_row * n_cols_ + dst_col];
            int stream_dst = mode == 1 ? stream_matrix_[dst_idx] : -1;
            if (mode == 1 && stream_src > 0 && stream_dst > 0) {
                continue;
            }
            flow_out_num_[index]++;
        }
        // Some flow direction data may cause errors after checking if all downslope cells are within mask
        // For example:
        //            (5,23)
        //            (6,23) (6,24)
        //            (7,23) (7,24) (7,25)
        //   Dinf: (6,24) has two downslope: (5,23) and (6,23), and both are outside the mask (subbasin)
        //   In fact, (7,25)'s elevation almost equals to (5,23), which is inside the mask.
        //   Due to the characteristics of Dinf algorithm, the (7,25) cannot be the downslope of (6,24)
        //   In such case, we should manually make the downslope of (6,25) -> (7,25) using elevation data
        //
        if (org_down_num >= 2 && flow_out_num_[index] == 0 && !(mode == 1 && stream_src > 0)) {
            FLTPT dem_diff = 0.;
            int max_flowidx = -1;
            FLTPT dem_dst;
            FLTPT dem_src = dem_->GetValue(i, j);
            for (int ii = 1; ii <= 8; ii++) {
                int dst_row = i + drow[ii];
                int dst_col = j + dcol[ii];
                if (!mask_->ValidateRowCol(dst_row, dst_col) || mask_->IsNoData(dst_row, dst_col)) {
                    continue;
                }
                dem_dst = dem_->GetValue(dst_row, dst_col);
                if (dem_src - dem_dst >= dem_diff) {
                    dem_diff = dem_src - dem_dst;
                    max_flowidx = ii;
                }
            }
            if (max_flowidx > 0) {
                flow_out_num_[index] = 1;
                flowdir_matrix_[index] = fdccw[max_flowidx];
            } else {
                cout << "The cell " << index << " cannot flow inside the mask, please check!" << endl;
            }
        }
    }
    flow_out_acc_[0] = flow_out_num_[0] < 0 ? 0 : flow_out_num_[0];
    flow_out_count_ = flow_out_num_[0] < 0 ? 0 : flow_out_num_[0];
    for (int idx = 1; idx < n_valid_cells_; idx++) {
        if (flow_out_num_[idx] == -1) {
            flow_out_acc_[idx] = flow_out_acc_[idx - 1];
            continue;
        }
        flow_out_count_ += flow_out_num_[idx];
        flow_out_acc_[idx] = flow_out_num_[idx] + flow_out_acc_[idx - 1];
    }
}

bool GridLayering::BuildFlowOutCellsArray() {
    int n_output = flow_out_count_ + n_valid_cells_ + 1;
    if (nullptr != flow_out_cells_) Release1DArray(flow_out_cells_);
    Initialize1DArray(n_output, flow_out_cells_, 0);
    int n_output2 = BuildMultiFlowOutArray(flowdir_matrix_, flow_out_num_,
                                           flow_out_cells_);
    if (n_output2 != n_output) {
        cout << "BuildFlowOutCellsArray failed!" << endl;
        return false;
    }
    return true;
}

bool GridLayering::Output2DimensionArrayTxt(const string &name, string &header,
                                            int* matrix, FLTPT* matrix2/* = nullptr */) {
    string outpath = string(output_dir_) + SEP + name + ".txt";
    std::ofstream ofs(outpath.c_str());
    ofs << matrix[0] << endl;
    ofs << header << endl;
    int tmp_count = 1;
    int tmp_count2 = 1;
    for (int i = 0; i < matrix[0]; i++) {
        int count = matrix[tmp_count++];
        ofs << i << "\t" << count << "\t";
        for (int j = 0; j < count; j++) {
            if (j == count - 1)
                ofs << matrix[tmp_count++];
            else
                ofs << matrix[tmp_count++] << ",";
        }
        if (nullptr != matrix2) {
            ofs << "\t";
            tmp_count2 = tmp_count - count;
            for (int k = 0; k < count; k++) {
                if (k == count - 1)
                    ofs << matrix2[tmp_count2++];
                else
                    ofs << matrix2[tmp_count2++] << ",";
            }
        }
        ofs << "\n"; // std::endl vs \n? https://stackoverflow.com/a/213977/4837280
    }
    ofs.close();
    return true;
}

#ifdef USE_MONGODB
bool GridLayering::OutputArrayAsGfs(const string &name, const vint length, FLTPT * const matrix) {
    bool flag = false;
    int max_loop = 3;
    int cur_loop = 1;
    while (cur_loop < max_loop) {
        if (!OutputToMongodb(name.c_str(), FLTPT_NAME, length, reinterpret_cast<char*>(matrix))) {
            cur_loop++;
        } else {
            cout << "Output " << name << " done!" << endl;
            flag = true;
            break;
        }
    }
    return flag;
}
bool GridLayering::OutputArrayAsGfs(const string &name, const vint length, int *const matrix) {
    bool flag = false;
    int max_loop = 3;
    int cur_loop = 1;
    while (cur_loop < max_loop) {
        if (!OutputToMongodb(name.c_str(), "INT32", length, reinterpret_cast<char *>(matrix))) {
            cur_loop++;
        } else {
            cout << "Output " << name << " done!" << endl;
            flag = true;
            break;
        }
    }
    return flag;
}
#endif


bool GridLayering::OutputFlowIn(int mode/*=0*/) {
    GetReverseDirMatrix(mode);
    if (!BuildFlowInCellsArray()) return false;

    int datalength = n_valid_cells_ + flow_in_count_ + 1;
    if (nullptr != flowin_fracs_) Release1DArray(flowin_fracs_);
    Initialize1DArray(datalength, flowin_fracs_, 0.f);
    flowin_fracs_[0] = CVT_FLT(n_valid_cells_);
    int count = 1;
    for (int valid_idx = 0; valid_idx < n_valid_cells_; valid_idx++) {
        flowin_fracs_[count++] = CVT_FLT(flow_in_num_[valid_idx]);
        if (flow_in_num_[valid_idx] < 0) {
            flowin_fracs_[count - 1] = 0.;
            continue;
        }
        for (int iin = 0; iin < flow_in_num_[valid_idx]; iin++) {
            int in_cell_idx = 1 + valid_idx + 1 + iin;
            if (valid_idx > 0) in_cell_idx += flow_in_acc_[valid_idx - 1];
            int source_index = flow_in_cells_[in_cell_idx];
            int fd_idx = find_flow_direction_index_ccw(pos_rowcol_[valid_idx][0] - pos_rowcol_[source_index][0],
                                                       pos_rowcol_[valid_idx][1] - pos_rowcol_[source_index][1]);

            FLTPT flowfrac = flowfrac_matrix_[source_index][fd_idx - 1];
            if (flowfrac < 0) continue;
            flowin_fracs_[count++] = flowfrac;
        }
    }

    if (count != datalength) {
        cout << "Build flow in fraction array failed!" << endl;
        return false;
    }

    string header = "ID\tUpstreamCount\tUpstreamID\tFlowInFraction";
    string outname = flowin_index_name_;
    string outname2 = flowin_frac_name_;
    if (mode == 1) {
        outname = flowin_index_hs_name_;
        outname2 = flowin_frac_hs_name_;
    }
    if (mode == 2) return true;
    bool done = Output2DimensionArrayTxt(outname, header, flow_in_cells_, flowin_fracs_);
    if (use_mongo_) {
#ifdef USE_MONGODB
        done = done && OutputArrayAsGfs(outname, count, flow_in_cells_) &&
                OutputArrayAsGfs(outname2, count, flowin_fracs_);
#endif
    }
    return done;
}


bool GridLayering::OutputFlowOut(int mode/*=0*/) {
    CountFlowOutCells(mode);
    if (!BuildFlowOutCellsArray()) return false;
    int datalength = flow_out_count_ + n_valid_cells_ + 1;
    if (nullptr != flowout_fracs_) Release1DArray(flowout_fracs_);
    Initialize1DArray(datalength, flowout_fracs_, 0.);

    flowout_fracs_[0] = CVT_FLT(n_valid_cells_);
    int count = 1;
    for (int valid_idx = 0; valid_idx < n_valid_cells_; valid_idx++) {
        int i = pos_rowcol_[valid_idx][0];
        int j = pos_rowcol_[valid_idx][1];
        int flowcount = flow_out_num_[valid_idx];
        flowout_fracs_[count++] = CVT_FLT(flowcount); // maybe 0
        if (flowcount <= 0) {
            flowout_fracs_[count - 1] = 0.;
            continue;
        }
        if (flowcount == 1) {
            int down_cell_idx = 1 + valid_idx + 1;
            if (valid_idx > 0) {
                down_cell_idx += flow_out_acc_[valid_idx - 1];
            }
            int down_cell = flow_out_cells_[down_cell_idx];
            int fd_idx = find_flow_direction_index_ccw(pos_rowcol_[down_cell][0] - i,
                                                       pos_rowcol_[down_cell][1] - j);
            for (int ii = 0; ii < 8; ii++) {
                flowfrac_matrix_[valid_idx][ii] = -1.;
            }
            flowfrac_matrix_[valid_idx][fd_idx - 1] = 1.;
            flowout_fracs_[count++] = 1.;
            continue;
        }
        vector<FLTPT> fracin(flowcount, 0.);
        vector<int> flowidxs(flowcount, -1);
        for (int iout = 0; iout < flow_out_num_[valid_idx]; iout++) {
            int down_cell_idx = 1 + valid_idx + 1 + iout;
            if (valid_idx > 0) {
                down_cell_idx += flow_out_acc_[valid_idx - 1];
            }
            int down_cell = flow_out_cells_[down_cell_idx];
            int fd_idx = find_flow_direction_index_ccw(pos_rowcol_[down_cell][0] - i,
                                                       pos_rowcol_[down_cell][1] - j);
            if (fd_idx < 0) {
                continue;
            }
            FLTPT curfract = flowfrac_matrix_[valid_idx][fd_idx - 1];
            if (curfract < 0) {
                cout << "No flow fraction found in the flow direction, "
                        "valid index: " << valid_idx << ", row: " << pos_rowcol_[valid_idx][0] <<
                        ", col: " << pos_rowcol_[valid_idx][1] <<
                        ", flow out count: " << flow_out_num_[valid_idx] <<
                        ", compressed direction: " << flowdir_matrix_[valid_idx] <<
                        ", component direction: " << fdccw[fd_idx] << "\n";
                return false;
            }
            flowout_fracs_[count++] = curfract;
            fracin[iout] = curfract;
            flowidxs[iout] = fd_idx - 1;
        }
        vector<FLTPT> fracout;
        normalize_flow_fraction(fracin, decimals_, fracout);
        for (int flow_idx = flowcount - 1; flow_idx >= 0; flow_idx--) {
            int actual_idx = flowcount - 1 - flow_idx;
            flowout_fracs_[count - 1 - flow_idx] = fracout[actual_idx];
            flowfrac_matrix_[valid_idx][flowidxs[actual_idx]] = fracout[actual_idx]; // write back
        }
    }

    if (count != datalength) {
        cout << "Build flow out fraction array failed!" << endl;
        return false;
    }

    string header = "ID\tDownstreamCount\tDownstreamID\tFlowOutFraction";
    string outname = flowout_index_name_;
    string outname2 = flowout_frac_name_;
    if (mode == 1) {
        outname = flowout_index_hs_name_;
        outname2 = flowout_frac_hs_name_;
    }
    if (mode == 2) return true;
    bool done = Output2DimensionArrayTxt(outname, header, flow_out_cells_, flowout_fracs_);
    if (use_mongo_) {
#ifdef USE_MONGODB
        done = OutputArrayAsGfs(outname, count, flow_out_cells_) &&
                OutputArrayAsGfs(outname2, count, flowout_fracs_);
#endif
    }
    return done;
}


bool GridLayering::GridLayeringFromSource(int mode/*=0*/) {
    if (nullptr != layers_updown_) Release1DArray(layers_updown_);
    Initialize1DArray(n_valid_cells_, layers_updown_, out_nodata_);
    if (!n_layer_cells_updown_.empty()) vector<vector<int> >().swap(n_layer_cells_updown_);

    int *flow_in_num_copy = nullptr;
    Initialize1DArray(n_valid_cells_, flow_in_num_copy, flow_in_num_);
    // indexes of cells in last layer
    int *last_layer = nullptr;
    Initialize1DArray(n_valid_cells_, last_layer, out_nodata_);
    int num_last_layer = 0; // number of cells in last layer

    // 1. find source grids, i.e., the first layer
    for (int i = 0; i < n_valid_cells_; i++) {
        if (flow_in_num_copy[i] == 0 && flowdir_matrix_[i] > 0) {
            last_layer[num_last_layer++] = i;
        }
    }
    // 2. loop layer-by-layer
    int num_next_layer = 0;
    // layering number of the current layer, at last, it's the total number of layers
    int cur_num = 0;
    // cell indexes in next layer
    int *next_layer = nullptr;
    Initialize1DArray(n_valid_cells_, next_layer, out_nodata_);
    int *tmp = nullptr; // swap variable
    int valid_idx = 0;
    vector<int> lyr_cells;
    while (num_last_layer > 0) {
        cur_num++;
        num_next_layer = 0;
        for (int i_in_layer = 0; i_in_layer < num_last_layer; i_in_layer++) {
            valid_idx = last_layer[i_in_layer];
            lyr_cells.emplace_back(valid_idx);
            layers_updown_[valid_idx] = cur_num;
            int dir = flowdir_matrix_[valid_idx];
            if (dir <= 0) {
                continue;
            }
            for (int out_idx = 0; out_idx < flow_out_num_[valid_idx]; out_idx++) {
                int out_cellidx = 1 + valid_idx + 1 + out_idx;
                if (valid_idx > 0) out_cellidx += flow_out_acc_[valid_idx - 1];
                int dst_posidx = flow_out_cells_[out_cellidx];
                if (--flow_in_num_copy[dst_posidx] == 0) {
                    next_layer[num_next_layer++] = dst_posidx;
                }
            }
        }
        vector<int>(lyr_cells).swap(lyr_cells);
        n_layer_cells_updown_.emplace_back(vector<int>(lyr_cells));
        lyr_cells.clear();

        num_last_layer = num_next_layer;
        tmp = last_layer;
        last_layer = next_layer;
        next_layer = tmp;
    }
    Release1DArray(last_layer);
    Release1DArray(next_layer);

    n_layer_count_ = CVT_INT(n_layer_cells_updown_.size());
    int n_valid_cells_new = 0;
    for (auto it = n_layer_cells_updown_.begin(); it != n_layer_cells_updown_.end(); ++it) {
        n_valid_cells_new += CVT_INT(it->size());
    }
    int length_new = n_valid_cells_new + n_layer_count_ + 1;
    if (nullptr != layer_cells_updown_) Release1DArray(layer_cells_updown_);
    Initialize1DArray(length_new, layer_cells_updown_, 0);
    layer_cells_updown_[0] = n_layer_count_;
    valid_idx = 1;
    for (auto it = n_layer_cells_updown_.begin();
         it != n_layer_cells_updown_.end(); ++it) {
        layer_cells_updown_[valid_idx++] = CVT_INT(it->size());
        for (auto it2 = it->begin(); it2 != it->end(); ++it2) {
            layer_cells_updown_[valid_idx++] = CVT_INT(*it2);
        }
    }
    Release1DArray(flow_in_num_copy);
    string outname = layering_updown_name_;
    if (mode == 1) outname = layering_updown_hs_;
    if (mode == 2) outname = layering_updown_ch_;
    bool done = OutputGridLayering(outname, layers_updown_, layer_cells_updown_);
    if (use_mongo_) {
#ifdef USE_MONGODB
        done = done && OutputArrayAsGfs(outname, length_new, layer_cells_updown_);
    }
#endif
    return done;
}

bool GridLayering::GridLayeringFromOutlet(int mode/*=0*/) {
    if (nullptr != layers_downup_) Release1DArray(layers_downup_);
    Initialize1DArray(n_valid_cells_, layers_downup_, out_nodata_);
    if (!n_layer_cells_downup_.empty()) vector<vector<int> >().swap(n_layer_cells_downup_);

    int *flow_out_num_copy = nullptr;
    Initialize1DArray(n_valid_cells_, flow_out_num_copy, flow_out_num_);
    // indexes of cells in last layer
    int *last_layer = nullptr;
    Initialize1DArray(n_valid_cells_, last_layer, out_nodata_);
    int num_last_layer = 0; // number of cells in last layer
    // 1. find outlet cells
    for (int i = 0; i < n_valid_cells_; i++) {
        if (flow_out_num_[i] == 0) {
            last_layer[num_last_layer++] = i;
        }
    }
    // 2. loop layer-by-layer
    int num_next_layer = 0;
    int *next_layer = nullptr;
    Initialize1DArray(n_valid_cells_, next_layer, out_nodata_);
    int *tmp = nullptr;
    vector<vector<int> > layer_tmp;
    int cur_num = 0;
    vector<int> lyr_cells;
    while (num_last_layer > 0) {
        cur_num++;
        num_next_layer = 0;
        for (int i_in_layer = 0; i_in_layer < num_last_layer; i_in_layer++) {
            int valid_idx = last_layer[i_in_layer];
            lyr_cells.emplace_back(valid_idx);
            layers_downup_[valid_idx] = cur_num;
            for (int in_idx = 0; in_idx < flow_in_num_[valid_idx]; in_idx++) {
                int in_cellidx = 1 + valid_idx + 1 + in_idx;
                if (valid_idx > 0) in_cellidx += flow_in_acc_[valid_idx - 1];
                int src_posidx = flow_in_cells_[in_cellidx];
                if (--flow_out_num_copy[src_posidx] == 0) {
                    next_layer[num_next_layer++] = src_posidx;
                }
            }
        }
        vector<int>(lyr_cells).swap(lyr_cells);
        layer_tmp.emplace_back(vector<int>(lyr_cells));
        lyr_cells.clear();

        num_last_layer = num_next_layer;
        tmp = last_layer;
        last_layer = next_layer;
        next_layer = tmp;
    }

    // 3. reverse the layer number
#pragma omp parallel for
    for (int i = 0; i < n_valid_cells_; i++) {
        if (!FloatEqual(layers_downup_[i], out_nodata_)) {
            layers_downup_[i] = cur_num - layers_downup_[i] + 1;
        }
    }
    Release1DArray(last_layer);
    Release1DArray(next_layer);

    n_layer_count_ = CVT_INT(layer_tmp.size());
    int n_valid_cells_new = 0;
    for (auto it = layer_tmp.begin(); it != layer_tmp.end(); ++it) {
        n_valid_cells_new += CVT_INT(it->size());
    }
    int length_new = n_valid_cells_new + n_layer_count_ + 1;
    if (nullptr != layer_cells_downup_) Release1DArray(layer_cells_downup_);
    Initialize1DArray(length_new, layer_cells_downup_, 0);
    layer_cells_downup_[0] = n_layer_count_;
    n_layer_cells_downup_.resize(n_layer_count_);
    int layer_idx = 0;
    int index = 1;
    for (auto it = layer_tmp.rbegin(); it != layer_tmp.rend(); ++it) {
        layer_cells_downup_[index++] = it->size();
        n_layer_cells_downup_[layer_idx++].assign(it->begin(), it->end());
        for (auto it2 = it->begin(); it2 != it->end(); ++it2) {
            layer_cells_downup_[index++] = *it2;
        }
    }
    Release1DArray(flow_out_num_copy);
    string outname = layering_downup_name_;
    if (mode == 1) outname = layering_downup_hs_;
    if (mode == 2) outname = layering_downup_ch_;
    bool done = OutputGridLayering(outname, layers_downup_, layer_cells_downup_);
    if (use_mongo_) {
#ifdef USE_MONGODB
        done = done && OutputArrayAsGfs(outname, length_new, layer_cells_downup_);
    }
#endif
    return done;
}

void RecomputeBoundsOne(int u, int K,
                        const vector<vector<int> > &up, const vector<vector<int> > &down,
                        const vector<int> &l, const vector<int> &lmin, const vector<int> &lmax,
                        int &low_u, int &high_u) {
    int max_up = INT_MIN;
    int min_dn = INT_MAX;
    if (up[u].empty() && down[u].empty()) {
        return;
    }
    for (size_t i = 0; i < up[u].size(); i++) {
        if (l[up[u][i]] > max_up) max_up = l[up[u][i]];
    }
    for (size_t i = 0; i < down[u].size(); i++) {
        if (l[down[u][i]] < min_dn) min_dn = l[down[u][i]];
    }
    int low_calc = (max_up == INT_MIN ? 0 : max_up + 1);
    int high_calc = (min_dn == INT_MAX ? (K - 1) : min_dn - 1);
    if (low_calc < lmin[u]) low_calc = lmin[u];
    if (high_calc > lmax[u]) high_calc = lmax[u];
    if (low_calc < 0) low_calc = 0;
    if (high_calc >= K) high_calc = K - 1;
    low_u = low_calc;
    high_u = high_calc;
}

//  Build topological order (Kahn), the graph MUST be DAG
void TopoOrder_Kahn(int N, const vector<vector<int> > &Up, const vector<vector<int> > &Down, vector<int> &topo) {
    vector<int> indeg(N, -1);
    for (int u = 0; u < N; u++) {
        if (Down[u].size() > 0 && indeg[u] == -1) indeg[u] = 0;
        for (size_t i = 0; i < Down[u].size(); i++) {
            if (indeg[Down[u][i]] == -1) indeg[Down[u][i]] = 0;
            indeg[Down[u][i]]++;
        }
    }
    std::queue<int> q;
    for (int u = 0; u < N; u++)
        if (indeg[u] == 0) q.push(u);

    topo.clear();
    topo.reserve(N);
    while (!q.empty()) {
        int u = q.front();
        q.pop();
        topo.push_back(u);
        for (size_t i = 0; i < Down[u].size(); ++i) {
            int v = Down[u][i];
            if (--indeg[v] == 0) q.push(v);
        }
    }
}

void InitMedianProjection_Strict(int N, int K, const vector<int> &Lmin, const vector<int> &Lmax,
                                 const vector<vector<int> > &Up, const vector<vector<int> > &Down, vector<int> &L) {
    vector<int> topo;
    TopoOrder_Kahn(N, Up, Down, topo);

    // Lower bounds (topological order)
    vector<int> Llo(N, 0);
    for (int idx = 0; idx < (int) topo.size(); ++idx) {
        int u = topo[idx];
        int lo = Lmin[u];
        for (size_t i = 0; i < Up[u].size(); ++i) {
            int p = Up[u][i];
            if (Llo[p] + 1 > lo) lo = Llo[p] + 1;
        }
        if (lo < 0) lo = 0;
        if (lo >= K) lo = K - 1;
        Llo[u] = lo;
    }
    // Upper bounds (reverse topological order)
    vector<int> Lhi(N, K - 1);
    for (int idx = (int) topo.size() - 1; idx >= 0; --idx) {
        int u = topo[idx];
        int hi = Lmax[u];
        if (hi >= K) hi = K - 1;
        for (size_t i = 0; i < Down[u].size(); ++i) {
            int c = Down[u][i];
            if (Lhi[c] - 1 < hi) hi = Lhi[c] - 1;
        }
        if (hi < 0) hi = 0;
        // lo>hi means the static window conflicts with DAG constraints, which theoretically will not happen
        if (Llo[u] > hi) hi = Llo[u];
        Lhi[u] = hi;
    }
    // Single forward feasible assignment, near the median
    L.assign(N, 0); // out: 0-based feasible init
    for (int idx = 0; idx < (int) topo.size(); ++idx) {
        int u = topo[idx];
        int req = 0;
        bool hasParent = false;
        for (size_t i = 0; i < Up[u].size(); ++i) {
            int p = Up[u][i];
            if (!hasParent || L[p] + 1 > req) {
                req = L[p] + 1;
                hasParent = true;
            }
        }
        int lo = Llo[u];
        if (hasParent && req > lo) lo = req;
        int hi = Lhi[u];
        // get median of [lo,hi]
        int mid = (Llo[u] + Lhi[u]) >> 1;
        if (mid < lo) mid = lo;
        if (mid > hi) mid = hi;
        L[u] = mid;
    }
}

void InitFromDownUpFeasible(int N, int K, const vector<int> &topo,
                            const vector<int> &L_down, const vector<int> &Lmin,
                            const vector<int> &Lmax, const vector<vector<int> > &Up,
                            const vector<vector<int> > &Down, vector<int> &L) {
    L = L_down;
    // forward: enforce lower & parents
    for (int idx = 0; idx < CVT_INT(topo.size()); idx++) {
        int u = topo[idx];
        if (L[u] < Lmin[u]) L[u] = Lmin[u];
        int req = -1;
        for (auto it = Up[u].begin(); it < Up[u].end(); ++it) {
            req = Max(req, L[*it] + 1);
        }
        if (req >= 0) L[u] = Max(L[u], req);
        if (L[u] > K - 1) L[u] = K - 1;
    }
    // backward: enforce upper & children
    for (int idx = CVT_INT(topo.size()) - 1; idx >= 0; --idx) {
        int u = topo[idx];
        int hi = Lmax[u];
        for (auto it = Down[u].begin(); it < Down[u].end(); ++it) {
            hi = Min(hi, L[*it] - 1);
        }
        if (hi < 0) hi = 0;
        if (L[u] > hi) L[u] = hi;
    }
    // forward again
    for (int idx = 0; idx < CVT_INT(topo.size()); ++idx) {
        int u = topo[idx];
        if (L[u] < Lmin[u]) L[u] = Lmin[u];
        int req = -1;
        for (auto it = Up[u].begin(); it < Up[u].end(); ++it) {
            req = Max(req, L[*it] + 1);
        }
        if (req >= 0) L[u] = Max(L[u], req);
        if (L[u] > K - 1) L[u] = K - 1;
    }
}

void ComputeStaticFeasibleBounds(int N, int K, const vector<int> &topo,
                                 const vector<int> &Lmin, const vector<int> &Lmax,
                                 const vector<vector<int> > &Up, const vector<vector<int> > &Down,
                                 vector<int> &low_star, vector<int> &high_star) {
    // low_star.assign(N, 0);
    // high_star.assign(N, K - 1);

    for (int idx = 0; idx < CVT_INT(topo.size()); idx++) {
        int u = topo[idx];
        int lo = Lmin[u];
        for (size_t i = 0; i < Up[u].size(); i++) {
            int p = Up[u][i];
            lo = Max(lo, low_star[p] + 1);
        }
        if (lo < 0) lo = 0;
        if (lo >= K) lo = K - 1;
        low_star[u] = lo;
    }
    for (int idx = CVT_INT(topo.size()) - 1; idx >= 0; idx--) {
        int u = topo[idx];
        int hi = Lmax[u];
        for (size_t i = 0; i < Down[u].size(); i++) {
            int c = Down[u][i];
            hi = Min(hi, high_star[c] - 1);
        }
        if (hi < 0) hi = 0;
        if (hi >= K) hi = K - 1;
        if (hi < low_star[u]) hi = low_star[u];
        high_star[u] = hi;
    }
}

bool GridLayering::GridLayeringEvenly(int mode/*=0*/) {
    // bool strict_deficit_target = true;
    bool accept_by_potential = true;
    bool allow_intermediate_fallback = true;
    // DeficitScanMode deficit_mode = NEAREST_FIRST;
    bool allow_evict_and_fill = true;
    bool auto_fix_suffix = true; // automatic detect and fix one or more the most downstream layers
    double depth_penalty_weight = 0.0; // 0 means close
    double scarcity_weight = 0.0; // penalty of scarce capacity, close by default

    if (nullptr != layers_evenly_) Release1DArray(layers_evenly_);
    Initialize1DArray(n_valid_cells_, layers_evenly_, out_nodata_);
    if (!n_layer_cells_evenly_.empty()) vector<vector<int> >().swap(n_layer_cells_evenly_);

    if (n_layer_cells_updown_.size() != n_layer_cells_downup_.size()) return false;
    const int N = n_valid_cells_;
    const int K = n_layer_count_;
    if (N <= 0 || K <= 0) return false;

    // Indexes of downstream cells
    vector<vector<int> > Down;
    Down.assign(n_valid_cells_, vector<int>());
    for (int i = 0; i < n_valid_cells_; i++) {
        int down_count = flow_out_num_[i];
        if (down_count <= 0) continue;
        Down[i].resize(down_count);
        for (int j = 0; j < down_count; j++) {
            int jj = 1 + i + 1 + j;
            if (i > 0) jj += flow_out_acc_[i - 1];
            Down[i][j] = flow_out_cells_[jj];
        }
    }
    // Indexes of upstream cells
    vector<vector<int> > Up;
    Up.assign(n_valid_cells_, vector<int>());
    for (int i = 0; i < n_valid_cells_; i++) {
        int up_count = flow_in_num_[i];
        if (up_count <= 0) continue;
        Up[i].resize(up_count);
        for (int j = 0; j < up_count; j++) {
            int jj = 1 + i + 1 + j;
            if (i > 0) jj += flow_in_acc_[i - 1];
            Up[i][j] = flow_in_cells_[jj];
        }
    }
    cout << "Valid cells count: " << n_valid_cells_ << ", layers count: " << n_layer_count_ << endl;
    // layer index (0-based) of each cell
    vector<int> L_up(n_valid_cells_), L_down(n_valid_cells_);
    for (int i = 0; i < n_valid_cells_; i++) {
        // when processing channel cells only, layers_updown_ and layers_downup_ may have many nodata
        if (layers_downup_[i] == out_nodata_ || layers_updown_[i] == out_nodata_) {
            L_up[i] = out_nodata_;
            L_down[i] = out_nodata_;
            continue;
        }
        L_up[i] = layers_updown_[i] - 1;
        L_down[i] = layers_downup_[i] - 1;
    }
    // static moving windows
    vector<int> Lmin(n_valid_cells_), Lmax(n_valid_cells_);
    for (int i = 0; i < n_valid_cells_; i++) {
        if (L_up[i] == out_nodata_ || L_down[i] == out_nodata_) {
            Lmin[i] = out_nodata_;
            Lmax[i] = out_nodata_;
            continue;
        }
        Lmin[i] = Min(L_up[i], L_down[i]);
        Lmax[i] = Max(L_up[i], L_down[i]);
    }
    // topological order
    vector<int> topo;
    TopoOrder_Kahn(N, Up, Down, topo);
    //int n_valid_cells_new = CVT_INT(topo.size());
    // initialize n_layer_cells_evenly_ (i.e., Buckets)
    vector<int> L;
    InitFromDownUpFeasible(N, K, topo, L_down, Lmin, Lmax, Up, Down, L);
    vector<vector<int> > Buckets(K);
    vector<int> Count(K, 0);
    for (int u = 0; u < N; u++) {
        if (L[u] == out_nodata_) continue;
        Buckets[L[u]].push_back(u);
        Count[L[u]]++;
    }
    int n_valid_cells_new = 0;
    for (vector<vector<int> >::iterator it = Buckets.begin(); it != Buckets.end(); ++it) {
        n_valid_cells_new += it->size();
    }
    // Deprecated initialization methods.
    // Option 1: use n_layer_cells_downup_ to initialize n_layer_cells_evenly_ (i.e., Buckets)
    // vector<int> L = L_down;
    // vector<vector<int> > Buckets = n_layer_cells_downup_;
    // vector<int> Count(K, 0);
    // for (auto it = Buckets.begin(); it != Buckets.end(); ++it) {
    //     Count[it - Buckets.begin()] = CVT_INT((*it).size());
    // }
    // Option 2:
    // vector<int> L;
    // InitMedianProjection_Strict(N, K, Lmin, Lmax, Up, Down, L);
    // vector<vector<int> > Buckets(K);
    // vector<int> Count(K,0);
    // for (int u = 0; u < N; u++) {
    //     Buckets[L[u]].push_back(u);
    //     Count[L[u]]++;
    // }

    // Compute dynamic low/high first, then determine fixed suffix layers
    vector<int> low(N, out_nodata_);
    vector<int> high(N, out_nodata_);
    for (int u = 0; u < N; u++) {
        RecomputeBoundsOne(u, K, Up, Down, L, Lmin, Lmax, low[u], high[u]);
    }
    // structural bounds
    vector<int> low_star(N, out_nodata_);
    vector<int> high_star(N, out_nodata_);
    ComputeStaticFeasibleBounds(N, K, topo, Lmin, Lmax, Up, Down, low_star, high_star);

    // heuristic fixed suffix by count threshold
    int fixed_suffix = 0;
    int prefix_end = K;
    bool fix_last_layer = true;
    if (mode == 1 && !stream_file_.empty()) {
        fix_last_layer = false;
    }

    if (auto_fix_suffix) {
        fixed_suffix = AutoDetectFixedSuffix_Heuristic(n_valid_cells_new, K, fix_last_layer,
                                                       Buckets, Count, low, &low_star);
        if (fixed_suffix < 0) fixed_suffix = 0;
        if (fixed_suffix > K) fixed_suffix = K;
    }
    prefix_end = K - fixed_suffix;
    cout << "Initial fixed layers cout: " << fixed_suffix << endl;

    // ideal target capacity of each layer, excluding fixed suffix layers
    vector<int> T(K, 0);
    int fixed_sum = 0;
    for (int l = prefix_end; l < K; l++) {
        T[l] = Count[l];
        fixed_sum += T[l];
    }
    int M = n_valid_cells_new - fixed_sum;

    vector<int> CapPrefix;
    ComputePrefixCapsExcludingSuffix(N, K, prefix_end, L, Lmin, Lmax, CapPrefix); /* prefix cap excluding suffix */
    BuildTargetsCappedWaterfillPrefix(/*R=*/prefix_end, /*K=*/K, /*M=*/M, /*Cap=*/CapPrefix, /*T=*/T);

    // cout << "Remin cells count: " << M << ", remained layers count: " << prefix_end << endl;
    // cout << "ID, Capacity, DOWNUP, Target" << endl;
    // for (int l = 0; l < prefix_end; l++) {
    //     cout << l << ", " << CapPrefix[l] << ", " << Count[l] << ", " << T[l] << endl;
    // }

    // main loop
    // for (;;) { // the same as while(true)
    vuint64_t max_iters = 10 * N + 5 * K;
    vuint64_t actual_iters = 0;
    int stall_rounds = 0;
    for (vuint64_t iter = 0; iter < max_iters; iter++) {
        actual_iters = iter;
        bool done = true;
        vector<int> S(K, 0); // surplus and deficit count of each layer, excluding fixed_suffix
        for (int l = 0; l < K; l++) {
            if (l < prefix_end) {
                S[l] = Count[l] - T[l];
                if (S[l] != 0) done = false; // The most strict condition.
            } else {
                S[l] = 0;
            }
        }
        if (done) break;

        bool progress = false;
#ifdef _DEBUG
        {
            long long phi_all = Phi_L1(Count, T);
            long long psi_all = Psi_L2(Count, T);
            /* use potential functions on prefix layers */
            long long phi_pref = Phi_L1_Prefix(Count, T, prefix_end);
            long long psi_pref = Psi_L2_Prefix(Count, T, prefix_end);
            std::printf("#iter=%d  fixed_suffix=%d  prefix_end=%d  Phi_all=%lld  Psi_all=%lld  Phi_pref=%lld  Psi_pref=%lld\n",
                iter, fixed_suffix, (K - fixed_suffix), phi_all, psi_all, phi_pref, psi_pref);

            vector<int> mov_up_dbg;
            vector<int> mov_dn_dbg;
            DebugComputeMovStats(Buckets, low, high, mov_up_dbg, mov_dn_dbg);
            DebugPrintSlice(K, /*show=*/3, Count, T, mov_up_dbg, mov_dn_dbg);
        }
#endif

        // Surplus layers in prefix layers, by descending surplus value
        vector<int> Surp;
        for (int l = 0; l < prefix_end; l++) {
            if (S[l] > 0) Surp.push_back(l);
        }
        /* Example:
         * S = { -3, 0, +2, +5, -1 };
         * // Only sorting surplus layers
         * Surp = { 2, 3 }; // i.e., S[2]=+2, S[3]=+5
         * std::sort() invoke comparator SurpCmp::operator()(int a, int b) to compare (2, 3):
         *   S[2]=2, S[3]=5 -> 5 is bigger -> return false -> 3 should be in front of 2
         * thus, Surp = { 3, 2 }
         */
        std::sort(Surp.begin(), Surp.end(), SurpCmp(S));

        for (size_t si = 0; si < Surp.size(); si++) {
            int s = Surp[si]; // layerID (0-based)
            int d = -1;
            vector<Candidate> cand;
            vector<int> CapTmp = CapPrefix;
            int capMin = 0;
            int capMax = 0;
            if (!CapTmp.empty()) {
                capMin = *std::min_element(CapTmp.begin(), CapTmp.end());
                capMax = *std::max_element(CapTmp.begin(), CapTmp.end());
            }
            bool ok = PickDeficitByPotentialAuto(s, S, K, prefix_end, Buckets, L, low, high, Lmin, Lmax, Up, Down,
                                                 Count, T, allow_intermediate_fallback, d, cand,
                                                 &CapTmp, capMin, capMax,
                                                 depth_penalty_weight, scarcity_weight);
            if (!ok) continue;

            int need = (S[s] < -S[d] ? S[s] : -S[d]);
            if (need <= 0) continue;

            // previous: calculate global phi1 and psi1
            // long long phi0 = Phi_L1(Count, T);
            // long long psi0 = Psi_L2(Count, T);
            long long phi0_pref = Phi_L1_Prefix(Count, T, prefix_end);
            long long psi0_pref = Psi_L2_Prefix(Count, T, prefix_end);

            vector<int> moved;
            vector<std::pair<int, int> > moved_pairs;
            for (size_t ci = 0; ci < cand.size() && need > 0; ci++) {
                int nu = cand[ci].u;
                int t = cand[ci].t;
                if (!(low[nu] <= t && t <= high[nu])) continue;
                if (t >= prefix_end) continue;
                int old = L[nu];
                if (old == t) continue;
                PlaceOne(nu, t, L, Buckets, Count);
                moved.push_back(nu);
                moved_pairs.push_back(std::make_pair(nu, old));
                need--;
            }
            if (!moved.empty()) {
                RefreshLocalBounds(moved, K, Up, Down, L, Lmin, Lmax, low, high);

                long long phi1_pref = Phi_L1_Prefix(Count, T, prefix_end);
                long long psi1_pref = Psi_L2_Prefix(Count, T, prefix_end);
                bool accept = (phi1_pref < phi0_pref) ||
                              (phi1_pref == phi0_pref && psi1_pref < psi0_pref);

#ifdef _DEBUG
                std::printf("  BATCH from s=%d to d=%d: moved=%d  Phi_pref:%lld->%lld  Psi_pref:%lld->%lld  %s\n",
                    s, d, (int)moved.size(), phi0_pref, phi1_pref, psi0_pref, psi1_pref,
                    accept ? "ACCEPT" : "REJECT");
#endif
                if (accept) {
                    progress = true;
                    break;
                }
                // rollback
                for (int irev = CVT_INT(moved_pairs.size()) - 1; irev >= 0; irev--) {
                    int nu = moved_pairs[irev].first;
                    int old = moved_pairs[irev].second;
                    PlaceOne(nu, old, L, Buckets, Count);
                }
                RefreshLocalBounds(moved, K, Up, Down, L, Lmin, Lmax, low, high);
            }
        }
        if (!progress) {
            if (TryEvictAndFillOnce(S, K, prefix_end, Buckets, L, Count,
                                    Lmin, Lmax, Up, Down, low, high, T)) {
                progress = true;
            }
        }

        if (!progress) {
            ++stall_rounds;
            if (stall_rounds >= 5) {
                int R_dyn = AutoDetectFixedSuffix_Heuristic(n_valid_cells_new, K, fix_last_layer,
                                                            Buckets, Count, low, &low_star);
                if (R_dyn > fixed_suffix) {
                    fixed_suffix = R_dyn;
                    prefix_end = K - fixed_suffix;

                    std::fill(T.begin(), T.end(), 0);
                    int fixed_sum2 = 0;
                    for (int l = prefix_end; l < K; l++) {
                        T[l] = Count[l];
                        fixed_sum2 += T[l];
                    }
                    int M2 = N - fixed_sum2;

                    vector<int> CapPrefix2;
                    ComputePrefixCapsExcludingSuffix(N, K, prefix_end, L, Lmin, Lmax, CapPrefix2);
                    BuildTargetsCappedWaterfillPrefix(prefix_end, K, M2, CapPrefix2, T);

                    stall_rounds = 0;
                    continue;
                }
            }
        } else {
            stall_rounds = 0;
        }
        if (!progress) break; // local optimum
    }
    //cout << "Iteration: " << actual_iters << endl;
    // outputs
    n_layer_cells_evenly_.assign(n_layer_count_, vector<int>());
    for (int u = 0; u < n_valid_cells_; u++) {
        int lu = L[u];
        if (lu == out_nodata_) continue;
        if (N == n_valid_cells_new) { // only if all cells are included for layering
            if (lu < 0) lu = 0;
            if (lu >= n_layer_count_) lu = n_layer_count_ - 1;
        }
        n_layer_cells_evenly_[lu].push_back(u);
        if (layers_evenly_) layers_evenly_[u] = lu + 1; // 1-based
    }

    // create output variables based on n_layer_cells_evenly_
    int datalength = n_valid_cells_new + n_layer_count_ + 1;
    if (nullptr != layer_cells_evenly_) Release1DArray(layer_cells_evenly_);
    Initialize1DArray(datalength, layer_cells_evenly_, out_nodata_);
    layer_cells_evenly_[0] = n_layer_count_;
    int valid_idx = 1;
    for (auto it = n_layer_cells_evenly_.begin(); it != n_layer_cells_evenly_.end(); ++it) {
        layer_cells_evenly_[valid_idx++] = CVT_INT(it->size());
        for (auto it2 = it->begin(); it2 != it->end(); ++it2) {
            layer_cells_evenly_[valid_idx++] = CVT_INT(*it2);
            layers_evenly_[*it2] = it - n_layer_cells_evenly_.begin() + 1;
        }
        if (valid_idx > datalength) {
            cout << "length exceed, please check!" << endl;
        }
    }
    string outname = layering_evenly_name_;
    if (mode == 1) outname = layering_evenly_hs_;
    if (mode == 2) outname = layering_evenly_ch_;
    bool done = OutputGridLayering(outname, layers_evenly_, layer_cells_evenly_);
    if (use_mongo_) {
#ifdef USE_MONGODB
        done = done && OutputArrayAsGfs(outname, datalength, layer_cells_evenly_);
    }
#endif
    return done;
}

#ifdef USE_MONGODB
bool GridLayering::OutputToMongodb(const char *name, const char* dtype, const vint number, char *s) {
    bson_t p = BSON_INITIALIZER;
    BSON_APPEND_INT32(&p, "SUBBASIN", subbasin_id_);
    BSON_APPEND_UTF8(&p, "TYPE", name);
    BSON_APPEND_UTF8(&p, "ID", name);
    BSON_APPEND_UTF8(&p, "DESCRIPTION", name);
    BSON_APPEND_INT32(&p, HEADER_RS_CELLSNUM, number);
    BSON_APPEND_UTF8(&p, HEADER_INC_NODATA, "FALSE");
    BSON_APPEND_UTF8(&p, HEADER_RS_DATATYPE, dtype);
    BSON_APPEND_UTF8(&p, HEADER_RSOUT_DATATYPE, dtype);

    gfs_->RemoveFile(string(name));
    vint n = -1;
    if (StringMatch(dtype, "INT32") || StringMatch(dtype, "INT")) {
        n = number * sizeof(int);
    } else if (StringMatch(dtype, "FLOAT") || StringMatch(dtype, "FLOAT32")) {
        n = number * sizeof(float);
    } else if (StringMatch(dtype, "DOUBLE") || StringMatch(dtype, "FLOAT32")) {
        n = number * sizeof(double);
    } else {
        return false;
    }
    gfs_->WriteStreamData(string(name), s, n, &p);
    bson_destroy(&p);
    if (nullptr == gfs_->GetFile(name)) {
        return false;
    }
    return true;
}
#endif

bool GridLayering::OutputGridLayering(const string &name,
                                      int *const layer_grid, int *const layer_cells) {
    string outpath = string(output_dir_) + "/" + name + ".tif";
    string header = "LayerID\tCellCount\tCellIDs";
    return IntRaster(mask_, layer_grid, n_valid_cells_).OutputFileByGdal(outpath)
           && Output2DimensionArrayTxt(name, header, layer_cells);
}
