/*!
 * \file MetadataInfoConst.h
 * \brief Define some const variables used by MetadataInfo class
 *
 * This file contains string constants for the MetadataInfo XML Schema.
 *
 * \author Junzhi Liu, Liangjun Zhu
 * \version 2.0
 * \date July 2023
 */
#ifndef SEIIMS_METADATA_INFO_CONST_H
#define SEIIMS_METADATA_INFO_CONST_H

#include <string>

using std::string;

//! XML Info file header
const string XMLHeader = "<?xml version='1.0' encoding='utf-8'?>\n<?xml-schema href='InfoXMLSchema.xsd'?>";
//! comment for XML file
const string XMLComment = "<!-- This file was auto-generated by the MetaDataInfo class. -->";
//! XML element tags
const string TagMetadata = "metadata";
const string TagMetadataAttributes = "version='0.4'";

const string TagClass = "class";
const string TagClassName = "name";
const string TagClassDescription = "description";

const string TagInformation = "information";
const string TagInfoId = "id";
const string TagInfoName = "name";
const string TagInfoDescription = "description";
const string TagInfoVersion = "version";
const string TagInfoAuthor = "author";
const string TagInfoEmail = "email";
const string TagInfoWebsite = "website";
const string TagInfoHelpfile = "helpfile";

const string TagParameters = "parameters";
const string TagParameter = "parameter";
const string TagInputs = "inputs";
const string TagInputVariable = "inputvariable";
const string TagOutputs = "outputs";
const string TagOutputVariable = "outputvariable";
const string TagInOutputs = "inoutputs";
const string TagInOutputVariable = "inoutputvariable";

const string TagVariableName = "name";
const string TagVariableUnits = "units";
const string TagVariableDescription = "description";
const string TagVariableSource = "source";
const string TagVariableDimension = "dimension";
const string TagVariableTransfer = "transfer";

const string TagDependencies = "dependencies";

/*!
 * \enum dimensionTypes
 * \ingroup module_setting
 * \brief enum of dimension data types
 */
enum dimensionTypes {
    DT_Unknown = -1,         /**< Unknown type */
    DT_Single = 0,           /**< Single floating point number */
    DT_SingleInt = 1,        /**< Single integer */
    DT_Array1DDateValue = 2, /**< 1D date array */
    DT_Array1D = 3,          /**< 1D floating point array, e.g., maximum temperature of sites */
    DT_Array1DInt = 4,       /**< 1D integer array */
    DT_Array2D = 5,          /**< 2D floating point array */
    DT_Array2DInt = 6,       /**< 2D integer array */
    DT_Raster1D = 7,         /**< Raster data in floating point number, same as DT_Array1D */
    DT_Raster1DInt = 8,      /**< Raster data in integer, same as DT_Array1DInt */
    DT_Raster2D = 9,         /**< 2D raster in floating point number, e.g., multi-layers of soil properties */
    DT_Raster2DInt = 10,     /**< 2D raster in integer, e.g., multiple flow direction */
    DT_Scenario = 11,        /**< Scenario used by BMPs */
    DT_Reach = 12,           /**< Reach parameters */
    DT_Subbasin = 13         /**< Subbasin instances */
};

/*!
 * \enum intervalTypes
 */
enum intervalTypes {
    TI_Unlimit = 0,     /**< Default, used for any time interval simulation */
    TI_Daily = 1,       /**< used for daily simulation */
    TI_Storm = 2        /**< used for sub-daily (storm) simulation */
};

/*!
 * \enum transferTypes
 * \ingroup module_setting
 * \brief Float values be transferred across subbasins for MPI version
 */
enum transferTypes {
    TF_None = 0,        /**< Default, which means no need to be transferred */
    TF_SingleValue = 1, /**< A single value in the data (e.g., DT_Array1D) */
    TF_OneArray1D = 2   /**< A piece of 1D array in the data (e.g., DT_Array2D) */
};

#endif /* SEIIMS_METADATA_INFO_CONST_H */
